<link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"></script>
<script>
$(function(){
   $("#fromDate").datetimepicker({dateFormat:'yy-mm-dd H:i',changeMonth: true,changeYear: true,yearRange:"1970:<?php echo date('Y')?>"});
   $("#toDate").datetimepicker({dateFormat:'yy-mm-dd H:i',changeMonth: true,changeYear: true,yearRange:"1970:<?php echo date('Y')?>"});

   $("#fromDate1").datetimepicker({dateFormat:'yy-mm-dd H:i',changeMonth: true,changeYear: true,yearRange:"1970:<?php echo date('Y')?>"});
   $("#toDate1").datetimepicker({dateFormat:'yy-mm-dd H:i',changeMonth: true,changeYear: true,yearRange:"1970:<?php echo date('Y')?>"});

});
</script>
<div class="pcoded-main-container">
    <div class="pcoded-content">
        <!-- [ breadcrumb ] start -->
    <div class="page-header">
        <div class="page-block">
            <div class="row align-items-center">
                <div class="col-md-12">
                    <div class="page-header-title">
                        <?php /* ?><h5 class="m-b-10">Welcome <?=sessionData('HCAP_ADMIN_FIRST_NAME')?></h5><?php */ ?>
                    </div>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="<?php echo getCurrentDashboardPath('dashboard/index'); ?>"><i class="feather icon-home"></i></a></li>
                        <li class="breadcrumb-item"><a href="javascript:void(0);">Recharge Coupons</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
        <!-- [ breadcrumb ] end -->
        <!-- [ Main Content ] start -->
     <div class="row">
          <div class="col-sm-12">
            <div class="card">
              <div class="card-header">
                <h5>Manage Recharge Coupons</h5>
                <a href="javaScriptcript:void{0}" class="btn btn-sm btn-primary pull-right" data-toggle="modal" data-target="#exportModal">Export excel</a>
                <a href="<?php echo getCurrentControllerPath('adminRecharges');?>" class="btn btn-sm btn-primary pull-right mr-2" >Admin Recharges</a>
              </div>
              <div class="card-body">
                <form id="Data_Form" name="Data_Form" method="get" action="<?php echo $forAction; ?>">
                  <div class="dt-responsive table-responsive">
                    <div id="simpletable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                      
                       <div class="row">
                        <div class="col-sm-12 col-md-12">
                          <div class="dataTables_length" id="simpletable_length">
                            <label>Show 
                              <select name="showLength" id="showLength" class="custom-select custom-select-sm form-control form-control-sm">
                                <option value="2" <?php if($perpage == '2')echo 'selected="selected"'; ?>>2</option>
                                <option value="10" <?php if($perpage == '10')echo 'selected="selected"'; ?>>10</option>
                                <option value="25" <?php if($perpage == '25')echo 'selected="selected"'; ?>>25</option>
                                <option value="50" <?php if($perpage == '50')echo 'selected="selected"'; ?>>50</option>
                                <option value="100" <?php if($perpage == '100')echo 'selected="selected"'; ?>>100</option>
                                <option value="All" <?php if($perpage == 'All')echo 'selected="selected"'; ?>>All</option>
                              </select>
                              entries
                            </label>
                          </div> 
                        </div>
                        

                        <div class="col-sm-3 col-md-3">
                          <select name="searchField" id="searchField" class="custom-select custom-select-sm form-control form-control-sm">
                            <option value="">Select Field</option>
                            <option value="coupon_code"  <?php if($searchField == 'coupon_code')echo 'selected="selected"'; ?>>Coupon Code</option>
                            <option value="rc_id"        <?php if($searchField == 'rc_id')echo 'selected="selected"'; ?>>Coupon Serial Number </option>
                            <option value="generated_by" <?php if($searchField == 'generated_by')echo 'selected="selected"'; ?>>Generated By(POS Number / Mobile Number ) </option>
                            <option value="redeemed_by"  <?php if($searchField == 'redeemed_by')echo 'selected="selected"'; ?>>Redeemed By (Mobile , Email)</option>
                            <option value="generate_for" <?php if($searchField == 'generate_for')echo 'selected="selected"'; ?>>Generated For</option>
                            <option value="status"       <?php if($searchField == 'status')echo 'selected="selected"'; ?>>Status (A = Active , I = Inavtive)</option>
                          </select>
                        </div>
                          
                        <div class="col-sm-3 col-md-3">
                          <input type="text" name="searchValue" id="searchValue" value="<?php echo $searchValue; ?>" class="form-control form-control-sm" placeholder="Enter Search Text">
                        </div>
                        <div class="col-sm-6 col-md-6">
                          <div class="row" >
                            <div class="col-sm-12 col-md-4">
                              <input type="text" name="fromDate" id="fromDate" autocomplete="off" value="<?php echo $fromDate; ?>" class="form-control form-control-sm" placeholder="From Date">
                            </div>
                            <div class="col-sm-12 col-md-4">
                              <input type="text" name="toDate" id="toDate" autocomplete="off" value="<?php echo $toDate; ?>" class="form-control form-control-sm" placeholder="To Date">
                            </div>
                            <div class="col-sm-12 col-md-4">
                              <input type="submit" name="Search" value="Search" class="btn btn-sm btn-primary">
                            </div>
                          </div>
                        </div>
                      </div>

                      <div class="row">
                        <div class="col-sm-12">
                          <div class="table-responsive">
                            <table id="simpletable" class="table table-striped table-bordered nowrap dataTable" role="grid" aria-describedby="simpletable_info">
                              <thead style="text-align: center;">
                                <tr role="row">
                                  <th width="5%" style="text-align: center;">S.No.</th>
                                  <th width="20%">Coupons Details</th>
                                  <th width="20%">Created By</th>
                                  <th width="20%">Redeemed By</th>
                                  <th width="10%" style="text-align: center;">Status</th>
                                  <th width="10%" style="text-align: center;">Created Date</th>
                                  <th width="10%">Action</th>
                                </tr>
                              </thead>
                              <tbody style="text-align: center;">
                                <?php if($ALLDATA <> ""): $i=$first; $j=0; foreach($ALLDATA as $ALLDATAINFO): 
                                if($j%2==0): $rowClass = 'odd'; else: $rowClass = 'even'; endif;
                                ?>
                                <tr role="row" class="<?php echo $rowClass; ?>">
                                  <td style="text-align: center;"><?=$i++?></td>
                                  <td>
                                      <br> <b>Serial No :-    </b> <?=$ALLDATAINFO['rc_id'];?>
                                      <br> <b>Coupon Code :-  </b> <?=stripslashes($ALLDATAINFO['coupon_code']);?> 
                                      <br> <b>Expring Date :- </b> <?=$ALLDATAINFO['expair_date'];?>
                                      <br> <b>UPoints :-      </b> <?=$ALLDATAINFO['coupon_code_amount'] ." AED"; ?>
                                  </td>
                                  <td>
                                    <?php
                                      if($ALLDATAINFO['created_user'] == "Admin" && !empty($ALLDATAINFO['created_by'])):

                                        $tblName           = 'uw_admin';
                                        $whereCon['where'] = array('admin_id' => (int)$ALLDATAINFO['created_by']);
                                        $Files             = array('admin_email','admin_phone');
                                        $UsersData         = $this->common_model->getParticularFieldByMultipleCondition($Files,$tblName , $whereCon  );

                                        $email      = $UsersData['admin_email'];
                                        $phone      = $UsersData['admin_phone'];
                                        $created_by = $ALLDATAINFO['created_user'];

                                      elseif($ALLDATAINFO['created_user'] != "Admin" && !empty($ALLDATAINFO['created_by'])):
                                       
                                        $tblName           = 'uw_users';
                                        $whereCon['where'] = array('users_id' => (int)$ALLDATAINFO['created_by']);
                                        $Files             = array('users_mobile','users_email','pos_number','store_name');
                                        $UsersData         = $this->common_model->getParticularFieldByMultipleCondition($Files,$tblName , $whereCon);
                                        
                                        $store_name  = $UsersData['store_name'];
                                        $phone       = $UsersData['users_mobile'];
                                        $created_by  = $ALLDATAINFO['created_user'];
                                        $pos_number  = $UsersData['pos_number'];
                                    ?>
                                      
                                    <?php else: ?> -- <?php endif;?>

                                    <?php if($UsersData['pos_number']):?>
                                      <br> <b>POS Number :-  </b> <?=$pos_number;?>
                                    <?php endif;?>
                                   
                                    <?php if($UsersData['store_name']):?>
                                      <br> <b>Store Name     :-  </b> <?=$store_name;?>
                                    <?php endif;?>

                                    <br> <b>Mobile      :-  </b> <?=$phone;?>
                                    <br> <b>Created By  :-  </b> <?=$created_by;?>
                                    <?php if($ALLDATAINFO['generate_for']): ?>
                                      <br> <b>Generated For :-  </b> <?=$ALLDATAINFO['generate_for'];?>
                                    <?php endif; ?>
                                  </td>
                                  <td>
                                      <?php 

                                          $UsersData1 = [];
                                          if($ALLDATAINFO['coupon_code_statys'] == "Redeemed"):

                                            $tblName             = 'uw_users';
                                            $whereCon22['where'] = array('users_id' => (int)$ALLDATAINFO['redeemed_by']);
                                            $Files               = array('users_mobile','users_email','pos_device_id', 'pos_number','users_name','last_name');
                                            $UsersData1          = $this->common_model->getParticularFieldByMultipleCondition($Files,$tblName , $whereCon22);
                                            
                                            $users_name    = $UsersData1['users_name'].' '.$UsersData1['last_name'];
                                            $email         = $UsersData1['users_email'];
                                            $phone         = $UsersData1['users_mobile'];
                                            $pos_number    = $UsersData1['pos_number'];
                                            $pos_device_id = $UsersData1['pos_device_id'];
                                          endif;

                                      if($UsersData1):  ?>


                                        <br> <b>Name           :-  </b> <?=$users_name;?>
                                        <br> <b>Email          :-  </b> <?=$email;?>
                                        <br> <b>Mobile         :-  </b> <?=$phone;?>
                                        <br> <b>Redeeming date :-  </b> <?=$ALLDATAINFO['modified_at'];?>
                                       
                                      <?php else:?>     
                                          --
                                      <?php endif;?>     

                                         
                                  </td>
                                  <td><?=showStatus($ALLDATAINFO['status'])?></td>
                                  <td><?=$ALLDATAINFO['created_at'];?></td>
                                  <td>
                                  <div class="btn-group">
                                    <?php if($ALLDATAINFO['status'] == 'A' && $ALLDATAINFO['coupon_code_statys'] == 'Active'): ?>
                                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action</button>
                                    <ul class="dropdown-menu" role="menu">
                                      <li><a href="<?php echo getCurrentControllerPath('changestatus/'.$ALLDATAINFO['_id']->{'$id'}.'/I')?>"><i class="fas fa-thumbs-down"></i> Inactive</a></li>
                                      <li><a href="<?php echo getCurrentControllerPath('cancellation/'.$ALLDATAINFO['_id']->{'$id'})?>" onClick="return confirm('Want to Cancel!');"><i class="fas fa-trash"></i> Cancel</a></li>
                                    <?php elseif($ALLDATAINFO['status'] == 'I'): ?>
                                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action</button>
                                    <ul class="dropdown-menu" role="menu">
                                      <li><a href="<?php echo getCurrentControllerPath('changestatus/'.$ALLDATAINFO['_id']->{'$id'}.'/A')?>"><i class="fas fa-thumbs-up"></i> Active</a></li>
                                    <?php endif; ?>
                                      
                                     </ul>
                                  </div>
                                  </td>
                                </tr>
                                <?php $j++; endforeach; else: ?>
                                <tr>
                                  <td colspan="8" style="text-align:center;">No Data Available In Table</td>
                                </tr>
                                <?php endif; ?>
                              </tbody>
                              </table>
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-sm-12 col-md-5">
                          <div class="dataTables_info" role="status" aria-live="polite"><?php echo $noOfContent; ?></div>
                        </div>
                        <div class="col-sm-12 col-md-7">
                          <div class="dataTables_paginate paging_simple_numbers">
                            <?php echo $PAGINATION; ?>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- [ Main Content ] end -->
    </div>
</div>

<div class="modal fade" id="exportModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Download Recharge Coupons</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="<?=getCurrentControllerPath('exportexcel')?>" method="post" autocomplete="off">
      <div class="modal-body">
          <div class="row">
            <div class="col-sm-12 col-md-6">
              <label for="recipient-name" class="col-form-label">Form:</label>
            </div>
            <div class="col-sm-12 col-md-6">
              <label for="recipient-name" class="col-form-label">To:</label>
            </div>
            <div class="col-sm-12 col-md-6">
              <input type="text" name="fromDate" id="fromDate1" value="<?php echo $fromDate; ?>" class="form-control form-control-sm" placeholder="From Date">
            </div>
            <div class="col-sm-12 col-md-6">
              <input type="text" name="toDate" id="toDate1" value="<?php echo $toDate; ?>" class="form-control form-control-sm" placeholder="From Date">
            </div>

            <div class="col-sm-12 col-md-6 col-lg-6 mt-2">
              <select name="searchField" id="searchField" class="custom-select custom-select-sm form-control form-control-sm">
                <option value="">Select Field</option>
                <option value="coupon_code"  <?php if($searchField == 'coupon_code')echo 'selected="selected"'; ?>>Coupon Code</option>
                <option value="rc_id"        <?php if($searchField == 'rc_id')echo 'selected="selected"'; ?>>Coupon Serial Number </option>
                <option value="generated_by" <?php if($searchField == 'generated_by')echo 'selected="selected"'; ?>>Generated By(POS Number / Mobile Number ) </option>
                <option value="redeemed_by"  <?php if($searchField == 'redeemed_by')echo 'selected="selected"'; ?>>Redeemed By (Mobile , Email)</option>
                <option value="generate_for" <?php if($searchField == 'generate_for')echo 'selected="selected"'; ?>>Generated For</option>
                <option value="status"       <?php if($searchField == 'status')echo 'selected="selected"'; ?>>Status (A = Active , I = Inavtive )</option>
              </select>
            </div>

            <div class="col-sm-12 col-md-6 col-lg-6 mt-2">
              <input type="text" name="searchValue" id="searchValue" value="<?php echo $searchValue; ?>" class="form-control form-control-sm" placeholder="Enter Search Text">
            </div>
            
          </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Download Report</button>
      </div>
      </form>
    </div>
  </div>
</div>